#ifndef KEYWORDS_H
#define KEYWORDS_H

static const char *lisp_keywords[] = {
    "block",
    "break",
    "case",
    "catch",
    "ccase",
    "cerror",
    "compiler-let",
    "cond",
    "ctypecase",
    "declaim",
    "declare",
    "declare",
    "defun",    // don't change this (needed in "highlightBlock")
    "defmacro", // -"-
    "(def(class|constant|generic|package|parameter|setf|struct|type|var))",
    "define-[a-z-]*",
    "destructuring-bind",
    "do",
    "do-[a-z-]*",
    "do*",
    "dolist",
    "dotimes",
    "ecase",
    "etypecase",
    "eval-when",
    "flet",
    "handler-bind",
    "handler-case",
    "if",
    "ignore-errors",
    "in-package",
    "inline",
    "labels",
    "lambda",
    "let",
    "let*",
    "locally",
    "loop",
    "macrolet",
    "proclaim",
    "prog",
    "prog*",
    "prog1",
    "prog2",
    "progn",
    "progv",
    "provide",
    "require",
    "restart-[a-z-]*",
    "return",
    "return-from",
    "symbol-macrolet",
    "tagbody",
    "the",
    "throw",
    "typecase",
    "unless",
    "unwind-protect",
    "when",
    "with-[a-z-]*",
    0};

#endif // KEYWORDS_H

